'use client'

import { useEffect, useMemo, useState } from 'react'
import { Header } from '@/components/Header'
import { VenueCard } from '@/components/VenueCard'
import { getVenues, type VenueRow } from '@/lib/database'

export default function VenuesPage() {
  const [venues, setVenues] = useState<VenueRow[]>([]); const [selectedCity, setSelectedCity] = useState('All'); const [selectedPriceRange, setSelectedPriceRange] = useState('all'); const [searchQuery, setSearchQuery] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { void getVenues().then(setVenues).catch((e: Error) => setError(e.message)).finally(() => setLoading(false)) }, [])
  const cities = useMemo(() => ['All', ...Array.from(new Set(venues.map((venue) => venue.city).filter((city): city is string => Boolean(city)))).sort()], [venues])
  const filtered = useMemo(() => venues.filter((venue) => { if (selectedCity !== 'All' && venue.city !== selectedCity) return false; const price = Number(venue.price_per_head); if (selectedPriceRange === '0-75' && price > 75) return false; if (selectedPriceRange === '75-125' && (price < 75 || price > 125)) return false; if (selectedPriceRange === '125-200' && (price < 125 || price > 200)) return false; if (selectedPriceRange === '200+' && price < 200) return false; const q = searchQuery.toLowerCase().trim(); return !q || [venue.name, venue.location, venue.description ?? '', ...venue.amenities].some((value) => value.toLowerCase().includes(q)) }), [venues, selectedCity, selectedPriceRange, searchQuery])
  return <><Header/><main className="min-h-screen bg-[#1a1a1a] text-white"><section className="sticky top-16 z-40 border-b border-white/10 bg-[#2d2d2d]"><div className="mx-auto max-w-7xl space-y-5 px-6 py-6"><input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search venues, locations, amenities…" className="w-full rounded-lg border border-white/10 bg-[#1a1a1a] px-4 py-3 outline-none"/><div className="flex flex-wrap items-center gap-2">{cities.map((city) => <button key={city} onClick={() => setSelectedCity(city)} className={`rounded-full px-3 py-2 text-sm ${selectedCity === city ? 'bg-white text-black' : 'bg-zinc-700 text-zinc-200'}`}>{city}</button>)}<select value={selectedPriceRange} onChange={(e) => setSelectedPriceRange(e.target.value)} className="ml-auto rounded-lg bg-zinc-700 px-3 py-2 text-sm"><option value="all">All prices</option><option value="0-75">Under $75/head</option><option value="75-125">$75–125/head</option><option value="125-200">$125–200/head</option><option value="200+">$200+/head</option></select></div></div></section><section className="mx-auto max-w-7xl px-6 py-10">{error ? <p className="rounded-lg bg-red-500/10 p-4 text-red-200">{error}</p> : loading ? <p className="text-zinc-400">Loading venues…</p> : filtered.length ? <><p className="mb-6 text-zinc-400">{filtered.length} live venue{filtered.length === 1 ? '' : 's'} available</p><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((venue) => <VenueCard key={venue.id} venue={venue}/>)}</div></> : <p className="text-zinc-400">No venues match those filters.</p>}</section></main></>
}
