'use client'

import { useCallback, useEffect, useState } from 'react'
import { CheckCircle2, Circle, Clock3, TriangleAlert } from 'lucide-react'
import { Header } from '@/components/Header'
import { getMyProfile, getMyTasks, updateTaskStatus, type TaskRow, type TaskStatus } from '@/lib/database'
import { useRouter } from 'next/navigation'

const styles: Record<TaskStatus, string> = { todo: 'bg-zinc-700 text-zinc-200', in_progress: 'bg-sky-500/15 text-sky-200', blocked: 'bg-red-500/15 text-red-200', completed: 'bg-emerald-500/15 text-emerald-200' }

export default function StaffDashboard() {
  const router = useRouter(); const [tasks, setTasks] = useState<TaskRow[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = useCallback(async () => { try { const profile = await getMyProfile(); if (!profile || profile.role !== 'staff') return router.replace('/unauthorized'); setTasks(await getMyTasks(profile.id)) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load tasks.') } finally { setLoading(false) } }, [router])
  useEffect(() => { void load() }, [load])
  async function changeStatus(id: string, status: TaskStatus) { try { await updateTaskStatus(id, status); await load() } catch (e) { setError(e instanceof Error ? e.message : 'Could not save status.') } }
  const counts = (status: TaskStatus) => tasks.filter((task) => task.status === status).length
  return <><Header/><main className="min-h-screen bg-[#101114] text-white"><div className="mx-auto max-w-6xl space-y-8 px-4 py-10 md:px-8"><section><p className="text-sm font-medium text-violet-300">MY WORK</p><h1 className="mt-1 text-4xl font-semibold">Task board</h1><p className="mt-2 text-zinc-400">Update the work state as it happens so your manager has an accurate event picture.</p></section>{error && <p className="rounded-lg bg-red-500/10 p-3 text-red-200">{error}</p>}<section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[Circle, 'To do', 'todo'], [Clock3, 'In progress', 'in_progress'], [TriangleAlert, 'Blocked', 'blocked'], [CheckCircle2, 'Done', 'completed']].map(([Icon, label, status]) => { const I = Icon as typeof Circle; return <div key={String(status)} className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><I size={18} className="text-violet-300"/><p className="mt-3 text-sm text-zinc-400">{String(label)}</p><p className="text-2xl font-semibold">{counts(status as TaskStatus)}</p></div> })}</section><section className="grid gap-4 md:grid-cols-2">{loading ? <p className="text-zinc-400">Loading assigned tasks…</p> : tasks.length === 0 ? <p className="rounded-xl border border-zinc-800 bg-zinc-900 p-5 text-zinc-400">You have no assigned tasks.</p> : tasks.map((task) => <article key={task.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-zinc-500">{task.booking?.venue?.name ?? 'Event'} · {task.phase}</p><h2 className="mt-1 font-semibold">{task.title}</h2><p className="mt-1 text-sm text-zinc-400">{task.description || 'No additional instructions.'}</p></div><span className={`h-fit rounded-full px-2 py-1 text-xs capitalize ${styles[task.status]}`}>{task.status.replace('_', ' ')}</span></div><div className="mt-4 flex items-center justify-between border-t border-zinc-800 pt-4"><span className="text-xs text-zinc-500">Due {task.due_date ?? 'not set'}</span><select aria-label={`Update ${task.title} status`} value={task.status} onChange={(e) => void changeStatus(task.id, e.target.value as TaskStatus)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-2 py-1 text-sm"><option value="todo">To do</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select></div></article>)}</section></div></main></>
}
