'use client'

import Image from 'next/image'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { MapPin, Users } from 'lucide-react'
import { Header } from '@/components/Header'
import { createBooking, getMyProfile, getVenue, type VenueRow } from '@/lib/database'

export default function VenuePage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [venue, setVenue] = useState<VenueRow | null>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { try { setVenue(await getVenue(id)) } catch (e) { setError(e instanceof Error ? e.message : 'Venue not found.') } }, [id])
  useEffect(() => { void load() }, [load])
  async function book(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!venue) return; const profile = await getMyProfile().catch(() => null); if (!profile) return router.push('/auth/login'); if (profile.role !== 'customer') return setError('Only customer accounts can create venue bookings.'); const form = new FormData(event.currentTarget); const guests = Number(form.get('guests')); if (!guests || guests > venue.capacity) return setError(`Guest count must be between 1 and ${venue.capacity}.`); setSaving(true); try { await createBooking({ venue_id: venue.id, event_date: String(form.get('date')), guest_count: guests, decoration_theme: String(form.get('decoration') || ''), catering_option: String(form.get('catering') || ''), entertainment_service: String(form.get('entertainment') || ''), special_requests: String(form.get('requests') || ''), total_price: guests * Number(venue.price_per_head) }, profile.id); router.push('/bookings') } catch (e) { setError(e instanceof Error ? e.message : 'Could not create booking.') } finally { setSaving(false) } }
  return <><Header/><main className="min-h-screen bg-[#101114] text-white"><div className="mx-auto max-w-6xl px-4 py-10 md:px-8">{error && <p className="mb-5 rounded-lg bg-red-500/10 p-3 text-red-200">{error}</p>}{!venue ? <p className="text-zinc-400">Loading venue…</p> : <div className="grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><section><div className="relative h-80 overflow-hidden rounded-2xl bg-zinc-800"><Image src={venue.images[0] || '/placeholder.jpg'} alt={venue.name} fill className="object-cover" priority/></div><p className="mt-6 text-sm font-medium text-sky-300">VENUE DETAILS</p><h1 className="mt-1 text-4xl font-semibold">{venue.name}</h1><div className="mt-3 flex flex-wrap gap-4 text-zinc-400"><span className="flex items-center gap-1"><MapPin size={16}/>{venue.location}</span><span className="flex items-center gap-1"><Users size={16}/>Up to {venue.capacity} guests</span></div><p className="mt-6 leading-7 text-zinc-300">{venue.description || 'No venue description has been added yet.'}</p><div className="mt-6 flex flex-wrap gap-2">{venue.amenities.map((item) => <span key={item} className="rounded-full bg-zinc-800 px-3 py-1 text-sm text-zinc-300">{item}</span>)}</div></section><aside className="h-fit rounded-2xl border border-zinc-800 bg-zinc-900 p-5"><p className="text-sm text-zinc-400">From</p><p className="text-3xl font-semibold">₹{Number(venue.price_per_head).toLocaleString()} <span className="text-sm font-normal text-zinc-400">/ guest</span></p><form onSubmit={book} className="mt-6 space-y-3"><label className="block text-sm">Event date<input name="date" required type="date" min={new Date().toISOString().slice(0, 10)} className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2"/></label><label className="block text-sm">Guests<input name="guests" required min="1" max={venue.capacity} type="number" className="mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2"/></label><input name="decoration" placeholder="Decoration preference" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"/><input name="catering" placeholder="Catering preference" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"/><input name="entertainment" placeholder="Entertainment preference" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"/><textarea name="requests" placeholder="Special requests" className="w-full rounded-lg border border-zinc-700 bg-zinc-950 p-2 text-sm"/><button disabled={saving} className="w-full rounded-lg bg-white px-4 py-3 text-sm font-semibold text-black disabled:opacity-60">{saving ? 'Submitting…' : 'Request booking'}</button></form></aside></div>}</div></main></>
}
